### PR TITLE
JPlag Frontend

### PR DESCRIPTION
**Pull request by PhilippMatthes**

### CODE REVIEW

**Comment by PhilippMatthes** [comment]
Today, I implemented the JPlag frontend features:

1. The admin pages `tasks/category` as well as `tasks/task` have a new action to check the selected tasks/categories for plagiarisms
2. The JPlag check saves to a new folder situated at `~/jplag-tests`, which is configurable in `settings.py`
3. When the admin opens the pages `tasks/category`, `tasks/task` or the plagiarism pages, he gets an information when there was a JPlag check. This is implemented in a new `PlagiarismAdmin` admin mode. The named admin models inhert their informative header from the `PlagiarismAdmin` model.
4. On the same page, the admin can download the zip archive of the JPlag output. 
5. The admin pages for `PlagiarismTest` and `DetectedPlagiarism` are now more informative due to new, custom `DetectedPlagiarismsAdmin` and `PlagiarismTestsAdmin` views.
6. I fixed an issue which we discussed in private.
7. Some more small things which I may have forgot about.

Here is a screenshot showing the downloadable zip file, the informative header and the custom action:
bildschirmfoto 2018-07-10 um 15 32 28

@martinmo there is a problem with Codacy, because I implemented custom list view fields like this:
```python
@admin.register(DetectedPlagiarism)
class DetectedPlagiarismsAdmin(PlagiarismAdmin):
    list_display = (
        'test',
        'author',
        'task',
        'veto',
    )

    # Here is where Codacy complains
    def author(self, obj):
        return obj.solution.author
    
    # Here as well
    def task(self, obj):
        return obj.solution.task
```
Should I remove these functions to ensure Codacy doesn't complain?

Here are the steps left until this feature can be merged:
1. Write some documentation
2. Test the new functions

**Comment by PhilippMatthes** [comment]
@martinmo I reverted this change for now so the Codacy tests will run through.

**Comment by PhilippMatthes** [comment]
I wrote new tests and introduced the jplag jar into a new lib folder. On top of this, I fixed a few minor issues. Next up: make the jplag checks asynchronous.

File: inloop/grading/models.py [hunk 1]
```diff
@@ -8,7 +9,29 @@ class PlagiarismTest(models.Model):
...
+
+    @property
+    def all_detected_plagiarisms(self):
+        """
+        Get all detected plagiarisms to this Test.
+        """
+        return DetectedPlagiarism.objects.filter(test=self, veto=False)
+
+    @property
+    def time_description(self):
```
Comment (PhilippMatthes) [inline inloop/grading/models.py]: As discussed in a meeting with @martinmo, time_description is already implemented by Django, so this function can be simplified.

File: inloop/settings.py [hunk 2]
```diff
@@ -206,3 +206,8 @@
 
 CONSTANCE_CONFIG.update(gitload_constance.config)
 CONSTANCE_CONFIG_FIELDSETS.update(gitload_constance.fieldsets)
+
+# Define the output path of the JPlag tests and their similarity factor
+JPLAG_JAR_PATH = str(BASE_DIR / "lib/jplag/jar/jplag.jar")
```
Comment (PhilippMatthes) [inline inloop/settings.py]: The jplag.jar should be moved one level up.

File: inloop/tasks/admin.py [hunk 3]
```diff
@@ -1,10 +1,84 @@
...
+jplag_check_tasks.short_description = 'Check tasks for Plagiarisms'
+jplag_check_category.short_description = 'Check category for Plagiarisms'
+
+
+def download_jplag_archive(request):
+    """
+    Create a downloadable archive and zip it into
+    a downloadable Response.
+    """
+    path_to_zip = make_archive(JPLAG_OUTPUT_PATH, "zip", JPLAG_OUTPUT_PATH)
```
Comment (PhilippMatthes) [inline inloop/tasks/admin.py]: As discussed in our meeting, the download zip function should be implemented as a list change action, and the zip files should be chached by the model.

File: inloop/tasks/admin.py [hunk 4]
```diff
@@ -1,10 +1,84 @@
...
+    response = HttpResponse(open(path_to_zip, 'rb'), content_type='application/zip')
+    response[
+        'Content-Disposition'
+    ] = 'attachment; filename=' + JPLAG_OUTPUT_PATH.replace(" ", "_") + '.zip'
+    return response
+
+
+class PlagiarismAdmin(admin.ModelAdmin):
```
Comment (PhilippMatthes) [inline inloop/tasks/admin.py]: Plagiarism admin should be moved to inloop/grading/admin.py.

File: tests/unit/grading/test_jplag.py [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+
+from django.core.files.uploadedfile import SimpleUploadedFile
+from django.test import TestCase
+
+from inloop.grading.copypasta import jplag_check
+from inloop.solutions.models import SolutionFile
+
+from tests.unit.grading.mixins import PlagiatedSolutionsData
+
+FIBONACCI = """
```
Comment (PhilippMatthes) [inline tests/unit/grading/test_jplag.py]: As discussed, we should add more sources to the test. I am thinking of two semantically different solutions and two solutions, one of which having extensive amounts of whitespaces. The whitespacing should not affect the plagiarism tests. The semantically different solutions should throw a similarity value less than, let's say 80%.

File: tests/unit/grading/test_models.py [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+            self.detected_plagiarism_alice
+            in self.plagiarism_test.all_detected_plagiarisms
+        )
+        self.assertTrue(
+            self.detected_plagiarism_bob
+            in self.plagiarism_test.all_detected_plagiarisms
+        )
+        self.assertEqual(self.plagiarism_test.all_detected_plagiarisms.count(), 2)
+
+    def test_time_description(self):
```
Comment (PhilippMatthes) [inline tests/unit/grading/test_models.py]: This test has to be removed, since this functionality will be covered already by Django tests.

File: inloop/grading/models.py (hunk 1 above)
Comment (martinmo) [reply inloop/grading/models.py]: Exaclty, it is located here: https://github.com/django/django/blob/stable/1.11.x/django/utils/timesince.py

File: inloop/settings.py (hunk 2 above)
Comment (martinmo) [reply inloop/settings.py]: Two levels -> `str(BASE_DIR / "lib/jplag-x.y.z.jar")`, and the filename should contain the release number of JPlag (should be on their GH releases page).

Comment (martinmo) [reply inloop/settings.py]: The release page says `lib/jplag-2.11.9-SNAPSHOT-jar-with-dependencies.jar`, but I think we can cut the name down to `lib/jplag-2.11.9-SNAPSHOT.jar`.

File: tests/unit/grading/test_jplag.py (hunk 5 above)
Comment (martinmo) [reply tests/unit/grading/test_jplag.py]: Ok, good idea, but I would prefer creating another pull request for more elaborate tests and getting this PR finished quicker.

File: tests/unit/grading/test_jplag.py [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+                min_similarity=100,
+                users=[self.alice, self.bob],
+                tasks=[self.task],
+                result_dir=path
+            )
+        self.assertTrue(self.passed_solution_bob in check)
+        self.assertTrue(self.passed_solution_alice in check)
+
+    def tearDown(self):
+        super().tearDown()
```
Comment (martinmo) [inline tests/unit/grading/test_jplag.py]: This statement should be the last in this method.

File: tests/unit/grading/test_jplag.py [hunk 8]
```diff
@@ -0,0 +1,66 @@
...
+    }
+
+    /*
+     * This string is just here for testing purposes.
+     */
+}
+"""
+
+
+class JPlagCheckTest(PlagiatedSolutionsData, TestCase):
```
Comment (martinmo) [inline tests/unit/grading/test_jplag.py]: We should think about tagging this test, because it is actually a slower integration test and not a unit test. For example, all tests involving Docker have the `slow` tag.

File: inloop/grading/models.py [hunk 9]
```diff
@@ -1,14 +1,61 @@
...
+    return "plagiarism_tests/{created_at}/{filename}".format_map({
+        "created_at": obj.created_at,
+        "filename": filename,
+    })
+
+
 class PlagiarismTest(models.Model):
     created_at = models.DateTimeField(auto_now_add=True)
     command = models.TextField(default="", help_text="Command that was used to perform the test")
+    zip_file = models.FileField(upload_to=get_upload_path, null=True)
```
Comment (martinmo) [inline inloop/grading/models.py]: The migration is missing. Please also commit the migrations file that Django `makemigrations` generates, otherwise it will only work on your computer.

File: inloop/grading/admin.py [hunk 10]
```diff
@@ -1,6 +1,66 @@
...
+        modeladmin.message_user(
+            request, "You can not download more or less than one zip file at a time."
+        )
+        return
+    test = queryset[0]
+    if not test.zip_file:
+        modeladmin.message_user(
+            request, "The selected plagiarism test has no downloadable zip file."
+        )
+    response = HttpResponse(open(test.zip_file.path, 'rb'), content_type='application/zip')
```
Comment (martinmo) [inline inloop/grading/admin.py]: Note to myself: in the long run, we cannot leave this, because this file object is not closed. This is related to #186, where I also need to implement a proper and secure mechanism to download (or display) uploaded files.

File: inloop/grading/admin.py [hunk 11]
```diff
@@ -1,6 +1,66 @@
...
+from django.http import HttpResponse
 
 from inloop.grading.models import DetectedPlagiarism, PlagiarismTest
 
-admin.site.register(DetectedPlagiarism)
-admin.site.register(PlagiarismTest)
+
+def download_jplag_zip(modeladmin, request, queryset):
+    """Fetch the stored jplag zip file and return it as a download"""
+    if queryset.count() != 1:
```
Comment (martinmo) [inline inloop/grading/admin.py]: Style: `len(queryset) != 1`

File: inloop/grading/admin.py [hunk 12]
```diff
@@ -1,6 +1,66 @@
...
+        return
+    test = queryset[0]
+    if not test.zip_file:
+        modeladmin.message_user(
+            request, "The selected plagiarism test has no downloadable zip file."
+        )
+    response = HttpResponse(open(test.zip_file.path, 'rb'), content_type='application/zip')
+    response[
+        'Content-Disposition'
+    ] = 'attachment; filename=' + 'JPlag_Output_' + str(test.created_at).replace(' ', '_') + '.zip'
```
Comment (martinmo) [inline inloop/grading/admin.py]: Style: you should use format strings instead.

File: inloop/grading/models.py [hunk 13]
```diff
@@ -1,14 +1,61 @@
...
+        Get all detected plagiarisms to this Test.
+        """
+        return DetectedPlagiarism.objects.filter(test=self, veto=False)
+
+    @property
+    def time_description(self):
+        """
+        Return a nicely formatted time description.
+        """
+        return timesince(self.created_at, now=timezone.now())
```
Comment (martinmo) [inline inloop/grading/models.py]: Style: why don't you use the `timesince` filter in the template?

File: inloop/templates/admin/tasks/plagiarism.html [hunk 14]
```diff
@@ -0,0 +1,24 @@
+{% extends 'admin/change_list.html' %} {% load i18n %}
+{% load staticfiles %}
+
+{% block object-tools %}
+
+    {% if test %}
+
+    <div style="margin-bottom: 75px; background-color: #79aec8; color: #fff; padding: 20px; border-radius: 20px; margin-right: 20px;">
+        Last plagiarism test: {{ test.created_at }} ({{ test.time_description }} ago) -
```
Comment (martinmo) [inline inloop/templates/admin/tasks/plagiarism.html]: Style: with the `timesince` filter/tag, it would look like `({{ test.created_at|timesince }} ago)`.

File: inloop/settings.py [hunk 15]
```diff
@@ -206,3 +206,8 @@
 
 CONSTANCE_CONFIG.update(gitload_constance.config)
 CONSTANCE_CONFIG_FIELDSETS.update(gitload_constance.fieldsets)
+
+# Define the output path of the JPlag tests and their similarity factor
+JPLAG_JAR_PATH = str(BASE_DIR / "lib/jplag-2.11.9-SNAPSHOT.jar")
+JPLAG_OUTPUT_PATH = str(BASE_DIR / "media/jplag/output")
```
Comment (martinmo) [inline inloop/settings.py]: This could be a temporary directory? Because at the end, we are only interested in the ZIP file which now gets saved in the model.

File: inloop/grading/admin.py (hunk 10 above)
Comment (PhilippMatthes) [reply inloop/grading/admin.py]: I changed this to 
```python
with open(test.zip_file.path, 'rb') as source:
    response = HttpResponse(source, content_type='application/zip')
```
Now the file will be closed automatically.

File: inloop/grading/admin.py (hunk 11 above)
Comment (PhilippMatthes) [reply inloop/grading/admin.py]: Fixed.

**Comment by martinmo** [comment]
Good work overall, I am looking forward to merge this as we shape it :-) My last inline comments were mainly style issues.

File: inloop/grading/admin.py (hunk 12 above)
Comment (PhilippMatthes) [reply inloop/grading/admin.py]: Fixed.

File: inloop/grading/models.py (hunk 13 above)
Comment (PhilippMatthes) [reply inloop/grading/models.py]: You are right, I removed this code replaced it in the template.

**Comment by PhilippMatthes** [comment]
The Travis CI is failing because it has problems with the JPlag output path. I will fix this now, making it a temporary directory.

File: inloop/grading/models.py (hunk 9 above)
Comment (PhilippMatthes) [reply inloop/grading/models.py]: Fixed.

**Comment by PhilippMatthes** [comment]
The Travis Build on Python 3.6 succeeds, on lower it runs into the following stack trace: 
```
Traceback (most recent call last):
  File "/home/travis/build/st-tu-dresden/inloop/tests/unit/grading/test_jplag.py", line 68, in test_jplag
    result_dir=path
  File "/home/travis/build/st-tu-dresden/inloop/inloop/grading/copypasta.py", line 49, in jplag_check
    save_plagiarism_set(plagiarism_set, path)
  File "/home/travis/build/st-tu-dresden/inloop/inloop/grading/models.py", line 75, in save_plagiarism_set
    path_to_zip = make_archive(result_dir, "zip", result_dir)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/shutil.py", line 777, in make_archive
    base_name = os.path.abspath(base_name)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/posixpath.py", line 358, in abspath
    if not isabs(path):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/posixpath.py", line 64, in isabs
    return s.startswith(sep)
AttributeError: 'PosixPath' object has no attribute 'startswith'
```
This may be due to the os support of Path, as mentioned in [this stackoverflow question](https://stackoverflow.com/questions/48195727/running-collectstatic-on-server-attributeerror-posixpath-object-has-no-attr). I will investigate this now.
